apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgw-k8s
  labels:
    app: dgw-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgw-k8s
  template:
    metadata:
      labels:
        app: dgw-k8s
    spec:
      containers:
        - name: dgw-k8s
          image: mikhamatta/dgw_k8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              ephemeral-storage: "2Gi"
            limits:
              ephemeral-storage: "4Gi"
          volumeMounts:
            - name: nextjs-app-config
              mountPath: "/app/.env.local"
              subPath: ".env.local"
              readOnly: true
      volumes:
        - name: nextjs-app-config
          configMap:
            name: nextjs-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: dgw-k8s-service
spec:
  ports:
    - port: 3000
      nodePort: 30001
  selector:
    app: dgw-k8s
  type: NodePort
