apiVersion: v1
kind: Secret
metadata:
  name: emailjs
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  NEXT_PUBLIC_EMAILJS_PRIVATE: eTllcURsSVcxWm5LekF4VnQK
