import Head from 'next/head';
import Image from 'next/image';
import styles from './index.module.css';
// export default function Home() {
const About = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>DGW | About</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://dgw.co.il'>DGW!</a>
        </h1>

        <p className={styles.description}>
          Website is{' '}
          <code className={styles.code}>
            {`under construction!`.toUpperCase()}
          </code>
        </p>
      </main>
    </div>
  );
};
export default About;
